log_wandb: True
wandb_name: Pretrained + KD_Generator
device: cuda
cuda_gpu: 0
server_pretrained: True
use_KD_Generator: True
seed: 0
dataset: FC100
log_dir: ./logs/
log_file_name: null
checkpoint_dir: ./checkpoints/
data_dir: ./data/
alg: fedavg
beta: 1
total_epoch: 1000
warmup_epoch: 0
num_classes: 100
dropout_p: 0.0
fine_tune_lr: 0.1

local_max_epoch: 100
loss: contrastive
lr: 0.001
meta_lr: 0.001
mode: few-shot
n_parties: 10
net_config:
  model: resnet18
  out_dim: 256
meta_config:
  num_train_tasks: 1
  fine_tune_steps: 5
  train_client_class: 20
  train_support_num: 2
  train_query_num: 15
  test_client_class: 5
  test_support_num: 5
  test_query_num: 15
  test_k: [1, 5]
generator_config:
  model_name: CGeneratorA
  n_cls: 100
  nz: 100
  nc: 3
  img_size: 32
KD_config:
  glb_model_lr: 0.1
  gen_model_lr: 0.01
  lr_decay_per_epoch: 0.99
  batch_size: 50
  weight_decay: 0.00001
  iterations: 10
  g_inner_round: 1
  d_inner_round: 5
  n_cls: 100

#

num_test_tasks: 10

num_true_test_ratio: 10
optimizer: sgd

partition: noniid
pool_option: FIFO
reg: 1.0e-05
sample_fraction: 1.0
server_momentum: 0
temperature: 0.5
word_vector: wiki.en.vec
wv_path: ./
finetune_ebd: false
induct_att_dim: 64
induct_hidden_dim: 100
induct_iter: 3
induct_rnn_dim: 128