K: 5
N: 5
Q: 5
alg: fedavg
bert_cache_dir: null
beta: 1
checkpoint_dir: ./checkpoints/
comm_round: 5000
datadir: ./data/
dataset: FC100
num_classes: 100
device: cuda:0
dropout_p: 0.0
epochs: 10
fine_tune_lr: 0.1
fine_tune_steps: 5
finetune_ebd: false
induct_att_dim: 64
induct_hidden_dim: 100
induct_iter: 3
induct_rnn_dim: 128
init_seed: 0
load_first_net: 1
load_model_file: null
load_model_round: null
load_pool_file: null
local_max_epoch: 100
log_file_name: null
logdir: ./logs/
loss: contrastive
lr: 0.001
meta_lr: 0.001
method: new
mode: few-shot
model: resnet18
model_buffer_size: 1
mu: 1
n_parties: 10
net_config:
  train_client_class: 15
  train_support_num: 2
  train_query_num: 2
  test_client_class: 5
  test_support_num: 5
  test_query_num: 5

normal_model: 0
num_test_tasks: 10
num_train_tasks: 1
num_true_test_ratio: 10
optimizer: sgd
out_dim: 256
partition: noniid
pool_option: FIFO
pretrained_bert: null
reg: 1.0e-05
sample_fraction: 1.0
save_model: 0
server_momentum: 0
temperature: 0.5
use_project_head: 1
word_vector: wiki.en.vec
wv_path: ./
server_pretrained: False
